[[_pdssallocationdeletion]]
= PDSs Allocation or Deletion

== Purpose

This is an optional z/OS Phase.

This phase is used to create or delete work PDS(s) as package PDS(s) for compiling for example.
This is done per object type based on the Environment parameters, e.g., the first qualifiers, the prefixes, ... defined in the environment properties file.

The functionality to allocate or delete PDSs is included by default in the <<CopySourcesBeforeCompilation.adoc#_id1695df0d0lg,Copy Sources to PDS for compilation>> and <<MapsProgramsCompilation.adoc#_id1695dd0l0vq,Maps and Programs compilation>> Phases.
Therefore, the _PDSs Allocation or Deletion_ phase may be used to complement the standard allocation/deletion of PDSs.

Example of usage: XMIT PDS to load PDS members of a different type as the compilation type (PDS, PDSE) and, next, to copy the members to real PDSs on the environment.

== Usage

The _PDSs Allocation or Deletion_ Phase can be used on Build and Deploy Environments.

This Phase is dependent on the <<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>> Phase.

== Parameters

[cols="1,1,1,1", frame="topbot", options="header"]
|===
| Parameter
| Mandatory/Optional
| Description
| Default Value

|alloc.command
|M
|Command for creating/deleting PDSs
|Create

|alloc.xmit
|M
|Option for allocating PDS with xmit qualifier instead of llq qualifier
|false

|alm.phase.builder
|M
|
|

|alm.phase.extractBundle
|M
|
|true

|alm.phase.mainScript
|M
|z/OS PDSs Allocation or Deletion
|zosAllocatePds.xml

|dir.zosModels
|O
|Models Location
|[alm_system]/[Machine]/PhaseModels 

|dir.zosResources
|O
|Property files Location
|[alm_system]/[Machine]/PhaseResources

|functions_list
|O
|List of Object Type Functions to select
|ALL

|objtypes_list
|O
|List of Object Types to select
|${project.objtypes}

|propsfile.environment
|O
|Property File of z/OS environment
|${dir.zosResources}/environment_deploy.properties

|propsfile.objtypes
|O
|Global Object Types file to use
|${dir.zosResources}/globalObjtypes.properties

|propsfile.parmsFTP
|O
|Property File of z/OS FTP or MFDAS system
|${dir.zosResources}/parmsFTPZOS.properties

|stopOnError
|O
|Option for stopping on error with z/OS activity.
|false
|===