= z/OS Build Phases

The following z/OS Phases can be used for the z/OS Build process (M = Mandatory, O = Optional). The table indicates which other Phase they are dependent on.
If there is no dependency, the Phase is working from the Source Environment location.

Click the name of one of the Phases in the table below to display all detailed information concerning the characteristics and usage of the Phase.

[cols="1,1,1", frame="topbot", options="header"]
|===
| M/O
| Build Phase
| Dependent on

|_M_
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>
|/

|_M_
|<<CopySourcesBeforeCompilation.adoc#_id1695df0d0lg,Copy Sources to PDS for compilation>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>

|_M_
|<<MapsProgramsCompilation.adoc#_id1695dd0l0vq,Maps and Programs compilation>>
|<<CopySourcesBeforeCompilation.adoc#_id1695df0d0lg,Copy Sources to PDS for compilation>>

|O
|<<ProperyFilesCreate.adoc#_id1695e070656,Create Property Files>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>

|O
|<<QMFFilesCreate.adoc#_id1695e0706sp,Create QMF Property Files>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>

|O
|<<CollectIdmsComponents.adoc#_id1695df00qvl,Collect Idms Components>>
|/

|O
|<<JmanJmodelsControl.adoc#_id1695e0704nk,Jman Jmodels Control>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>

|O
|<<ListFilesFromLocation.adoc#_id16cnb0n0278,List Files from location to CSV or Excel file>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>

|O
|<<PDSAllocationDeletion.adoc#_pdssallocationdeletion,PDSs Allocation or Deletion>>
|<<CopyFromSourceTarget.adoc#_id1695k0k0ijd,Copy from Source to Target>>
|===

== Mandatory Phases

There are three basic, mandatory, z/OS Build Phases. 

They complement two Kobee core Phases, i.e., the __Retrieve
Code __Phase (retrieving the content from the VCR into Kobee) and the _Transport Source_ Phase (transferring the Source files to the Kobee Source location).

[cols="1,1,1", frame="topbot", options="header"]
|===
| Sequence
| Solution Phase
| Usage

|_1_
|Copy from Source to Target
|This Phase selects the files that need to be copied, using predefined filters and include/exclude masks.
Next, the selected files are copied from the Source location on the Kobee Agent to the Target location on the Kobee Agent.
The following Phases in the sequence will only use the copied files from this Target location.

|_2_
|Copy Sources to PDS for compilation
|This Phase copies the files (object types specified in the properties files) from the Target location on the Kobee Agent into temporary PDSs on the z/OS Platform.
Before the file transfers, temporary PDSs will be created, as well as the PDSs necessary for compiling the files selected in the next Phase.

|_3_
|Maps and Programs compilation
|This Phase creates the compile JCL, submits the job and runs the actual compilation on z/OS for each Map and next each program.

After the compilation, the Phase will control the result and collect all resulting files generated by the compile job (listing, load modules, generated DB2 dbrm files, ...) in the target location for adding to the Kobee Archive.
|===

_IMPORTANT:_

The following sequence rules must be followed.

* The mandatory Phases must be used in the sequence order specified in the table above.
* The other (optional) Build Phases may be inserted in between or after the mandatory Phases, in any order required. 
+
Exception: The optional __Collect Idms Components __Phase starts from the Source location and only copies and controls IDMS components.
It is not dependent on any of the other Phases and, if required, it may be executed before the _Copy from
Source to Target_ Phase.


== Optional Phases

The other Build Phases are for specific usage and can be inserted wherever they are needed in the lifecycle.